import { neon } from '@neondatabase/serverless'
import type { BandcampTrack } from './bandcamp.js'

export const migration = [
 `CREATE EXTENSION IF NOT EXISTS pgcrypto`,
 `CREATE TABLE IF NOT EXISTS tracks_cache(track_id text PRIMARY KEY,album_id text,artist_id text,title text NOT NULL,artist text NOT NULL,album text NOT NULL,duration_seconds integer NOT NULL,genre text,year integer,source_created_at timestamptz,cover_art_id text,bitrate integer,content_type text,country text,subgenres jsonb NOT NULL DEFAULT '[]',tags jsonb NOT NULL DEFAULT '[]',last_seen_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS track_preferences(track_id text PRIMARY KEY,liked boolean NOT NULL DEFAULT false,disliked boolean NOT NULL DEFAULT false,updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS listening_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,track_id text NOT NULL,listened_ms integer NOT NULL DEFAULT 0,duration_ms integer,completed boolean NOT NULL DEFAULT false,skipped_early boolean NOT NULL DEFAULT false,repeated boolean NOT NULL DEFAULT false,queue_context jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS track_stats(track_id text PRIMARY KEY,plays integer NOT NULL DEFAULT 0,completes integer NOT NULL DEFAULT 0,skips_early integer NOT NULL DEFAULT 0,repeats integer NOT NULL DEFAULT 0,total_listened_ms bigint NOT NULL DEFAULT 0,last_played_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS app_state(id text PRIMARY KEY,state jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS user_preferences(id text PRIMARY KEY,settings jsonb NOT NULL,last_collection_scan_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS push_subscriptions(endpoint text PRIMARY KEY,p256dh text NOT NULL,auth text NOT NULL,expiration_time bigint,user_agent text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS playlists(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,source text NOT NULL DEFAULT 'heavycamp',bandcamp_playlist_id text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
 `CREATE TABLE IF NOT EXISTS playlist_tracks(playlist_id uuid NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,track_id text NOT NULL,position integer NOT NULL,added_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(playlist_id,track_id))`,
 `CREATE INDEX IF NOT EXISTS listening_events_track_idx ON listening_events(track_id,created_at DESC)`,
 `CREATE INDEX IF NOT EXISTS playlist_tracks_position_idx ON playlist_tracks(playlist_id,position)`
]
function sql(){const u=process.env.DATABASE_URL;if(!u)throw new Error('DATABASE_URL is not configured');return neon(u)}
export const dbConfigured=()=>Boolean(process.env.DATABASE_URL)
export async function bootstrap(){const q=sql() as any;for(const s of migration)await q.query(s,[])}
export async function syncTracks(tracks:BandcampTrack[]){const q=sql();for(const t of tracks)await q`INSERT INTO tracks_cache(track_id,album_id,artist_id,title,artist,album,duration_seconds,genre,year,source_created_at,cover_art_id,bitrate,content_type,last_seen_at,updated_at) VALUES(${t.id},${t.albumId||null},${t.artistId||null},${t.title},${t.artist},${t.album},${t.duration},${t.genre||null},${t.year||null},${t.created&&Date.parse(t.created)?new Date(t.created).toISOString():null},${t.coverArt||null},${t.bitRate||null},${t.contentType||null},now(),now()) ON CONFLICT(track_id) DO UPDATE SET title=excluded.title,artist=excluded.artist,album=excluded.album,duration_seconds=excluded.duration_seconds,genre=excluded.genre,year=excluded.year,cover_art_id=excluded.cover_art_id,bitrate=excluded.bitrate,content_type=excluded.content_type,last_seen_at=now(),updated_at=now()`}
export async function userData(){const q=sql();const [s,st,prefs,stats]=await Promise.all([q`SELECT settings FROM user_preferences WHERE id='main' LIMIT 1`,q`SELECT state FROM app_state WHERE id='main' LIMIT 1`,q`SELECT track_id AS "trackId",liked,disliked FROM track_preferences`,q`SELECT track_id AS "trackId",plays,completes,skips_early AS "skipsEarly",repeats,total_listened_ms AS "totalListenedMs",last_played_at AS "lastPlayedAt" FROM track_stats`]);return{settings:s[0]?.settings||null,state:st[0]?.state||null,preferences:prefs,stats}}
export async function preference(trackId:string,value:string){const q=sql(),liked=value==='liked',disliked=value==='disliked';await q`INSERT INTO track_preferences(track_id,liked,disliked,updated_at) VALUES(${trackId},${liked},${disliked},now()) ON CONFLICT(track_id) DO UPDATE SET liked=${liked},disliked=${disliked},updated_at=now()`}
export async function saveState(state:unknown){await sql()`INSERT INTO app_state(id,state,updated_at) VALUES('main',${JSON.stringify(state)}::jsonb,now()) ON CONFLICT(id) DO UPDATE SET state=excluded.state,updated_at=now()`}
export async function saveSettings(settings:unknown){await sql()`INSERT INTO user_preferences(id,settings,updated_at) VALUES('main',${JSON.stringify(settings)}::jsonb,now()) ON CONFLICT(id) DO UPDATE SET settings=excluded.settings,updated_at=now()`}
export async function history(b:any){const q=sql(),ms=Math.max(0,Math.round(Number(b.listenedMs||0))),done=Boolean(b.completed),skip=Boolean(b.skippedEarly),repeat=Boolean(b.repeated);await q`INSERT INTO listening_events(track_id,listened_ms,duration_ms,completed,skipped_early,repeated,queue_context) VALUES(${String(b.trackId)},${ms},${b.durationMs?Math.round(Number(b.durationMs)):null},${done},${skip},${repeat},${JSON.stringify(b.queueContext||{})}::jsonb)`;await q`INSERT INTO track_stats(track_id,plays,completes,skips_early,repeats,total_listened_ms,last_played_at,updated_at) VALUES(${String(b.trackId)},1,${done?1:0},${skip?1:0},${repeat?1:0},${ms},now(),now()) ON CONFLICT(track_id) DO UPDATE SET plays=track_stats.plays+1,completes=track_stats.completes+${done?1:0},skips_early=track_stats.skips_early+${skip?1:0},repeats=track_stats.repeats+${repeat?1:0},total_listened_ms=track_stats.total_listened_ms+${ms},last_played_at=now(),updated_at=now()`}
export async function getPlaylists(){const q=sql();const p=await q`SELECT id::text,name,source,bandcamp_playlist_id AS "bandcampPlaylistId" FROM playlists ORDER BY created_at`;const t=await q`SELECT playlist_id::text AS "playlistId",track_id AS "trackId" FROM playlist_tracks ORDER BY position`;return p.map(x=>({...x,trackIds:t.filter(y=>y.playlistId===x.id).map(y=>y.trackId)}))}
export async function playlistAction(b:any){const q=sql();if(b.action==='create'){const r=await q`INSERT INTO playlists(name) VALUES(${String(b.name).trim()}) RETURNING id::text,name,source,bandcamp_playlist_id AS "bandcampPlaylistId"`;return{...r[0],trackIds:[]}}if(b.action==='add'){const rows=await q`SELECT COALESCE(MAX(position),-1)+1 AS p FROM playlist_tracks WHERE playlist_id=${String(b.playlistId)}::uuid`;await q`INSERT INTO playlist_tracks(playlist_id,track_id,position) VALUES(${String(b.playlistId)}::uuid,${String(b.trackId)},${Number(rows[0]?.p||0)}) ON CONFLICT DO NOTHING`;return{ok:true}}throw new Error('Unknown playlist action')}
export async function savePush(s:any,ua:string|null){await sql()`INSERT INTO push_subscriptions(endpoint,p256dh,auth,expiration_time,user_agent,updated_at) VALUES(${s.endpoint},${s.keys.p256dh},${s.keys.auth},${s.expirationTime||null},${ua},now()) ON CONFLICT(endpoint) DO UPDATE SET p256dh=excluded.p256dh,auth=excluded.auth,expiration_time=excluded.expiration_time,user_agent=excluded.user_agent,updated_at=now()`}
export async function scanState(){const q=sql();const ids=await q`SELECT track_id FROM tracks_cache`;const pref=await q`SELECT settings,last_collection_scan_at FROM user_preferences WHERE id='main'`;const subs=await q`SELECT endpoint,p256dh,auth FROM push_subscriptions`;return{ids:new Set(ids.map(x=>x.track_id)),settings:(pref[0]?.settings||{}) as any,last:pref[0]?.last_collection_scan_at,subs}}
export async function markScan(){const q=sql();await q`INSERT INTO user_preferences(id,settings,last_collection_scan_at,updated_at) VALUES('main','{}'::jsonb,now(),now()) ON CONFLICT(id) DO UPDATE SET last_collection_scan_at=now(),updated_at=now()`}
